### ISSUE TITLE
TelegramMonitor callback super()

### ISSUE THREAD

**Issue by cicobalico** [hadim/keras-toolbox#1]
Hi @hadim,
first of all thank you for the amazing work you're doing, hope to be able to help a little in the future even if I'm just starting to learn

I think I found an issue in the TelegramMonitor Callback
running this simple script I get this error:

``` python
from kerastoolbox.callbacks import TelegramMonitor
monitor = TelegramMonitor(api_token="<mytoken>", chat_id=<myid>, plot_history=2)
```

`File "/usr/local/lib/python2.7/dist-packages/kerastoolbox/callbacks.py", line 135, in __init__
    super().__init__(**kwargs)
TypeError: super() takes at least 1 argument (0 given)`

am I doing something wrong?

Edit: I submitted a pull request of a fix that works for me. #2

**Comment by hadim** [comment]
This is an only Python 3 feature. See #2 for the discussion.
